trigger:
  branches:
    include:
      - main 

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: 'kysvccnxn'  
  acrName: 'kyproj3-acr' 
  imageName: 'styleapp' 
  dockerfilePath: './Dockerfile'  
  containerRegistryUrl: '$(acrName).azurecr.io'  

stages:
  - stage: Build
    displayName: 'Build and Push Docker Image'
    jobs:
      - job: BuildAndPush
        displayName: 'Build and Push Docker Image to ACR'
        steps:
          - task: Checkout@1
            displayName: 'Checkout Repository'

          - task: Docker@2
            displayName: 'Build Docker Image'
            inputs:
              containerRegistry: $(azureSubscription)  
              repository: $(containerRegistryUrl)/$(imageName)  
              command: 'buildAndPush'  
              Dockerfile: $(dockerfilePath)  
              tags: 'latest'  