apiVersion: apps/v1
kind: Deployment
metadata:
  name: styleapp
  labels:
    app: styleapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: styleapp
  template:
    metadata:
      labels:
        app: styleapp
    spec:
      containers:
      - name: styleapp
        image: kyproj3-acr.azurecr.io/styleapp:latest 
        ports:
        - containerPort: 80  
        imagePullPolicy: Always
      imagePullSecrets:
      - name: acr-secret  # ACR Service Connection
---
apiVersion: v1
kind: Service
metadata:
  name: styleapp-service
spec:
  selector:
    app: styleapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  clusterIP: None  # Set to None for headless service if you need DNS resolution
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: styleapp-ingress
  annotations:
    appgw.ingress.kubernetes.io/backend-path-prefix: "/" 
    appgw.ingress.kubernetes.io/ssl-redirect: "false"  
    kubernetes.io/ingress.class: "azure/application-gateway" 
spec:
  rules:
  - host: 52.176.13.157
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: styleapp-service
            port:
              number: 80
